#!/bin/sh
#
# Blink the onboard LED

GPIO=$1

cleanup() { # Release the GPIO port
  echo $GPIO > /sys/class/gpio/unexport
  exit
}

# Open the GPIO port
#
echo $GPIO > /sys/class/gpio/export 

#trap cleanup SIGINT # call cleanup on Ctrl-C
 echo "out" > /sys/class/gpio/gpio$GPIO/direction 
# Blink forever
while [ "1" = "1" ]; do
  echo "0" > /sys/class/gpio/gpio$GPIO/value 
  sleep 1
  echo "1" > /sys/class/gpio/gpio$GPIO/value  
  sleep 1
done

cleanup # call the cleanup routine

